# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 책 조회 (없는 책)
GET http://localhost:8070/books/200
Content-Type: application/json

### 책 조회
GET http://localhost:8070/books/1
Content-Type: application/json

### 책 전체 리스트 조회
GET http://localhost:8070/books
Content-Type: application/json

###


