# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 판매자 생성(잘못된 파라미터)
POST http://localhost:8070/seller
Content-Type: application/json

{
  "id": "test",
  "password": "1234",
  "name": "한소진",
  "phoneNumber": "010-1234-567",
  "email": "naver.com",
  "address": "행당동"
}

### 판매자 생성(중복)
POST http://localhost:8070/seller
Content-Type: application/json

{
  "id": "rosie",
  "password": "1234",
  "name": "한소진",
  "phoneNumber": "010-1234-5678",
  "email": "rosie@naver.com",
  "address": "행당동"
}

### 판매자 생성(정상)
POST http://localhost:8070/seller
Content-Type: application/json

{
  "id": "rosie2",
  "password": "1234",
  "name": "한소진",
  "phoneNumber": "010-1234-5678",
  "email": "rosie@naver.com",
  "address": "행당동"
}

###판매자 조회(없는 아이디)
GET http://localhost:8070/seller/roo
Content-Type: application/json

###판매자 조회(정상)
GET http://localhost:8070/seller/rosie
Content-Type: application/json

###
