# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Cookie
GET http://localhost:8070/cookie
Cookie: user=ppiyo

### 로컬
GET http://localhost:8070/hello

### 개발 오류
GET http://localhost:8070/dev/hello

### 개발 정상
GET http://localhost:8070/dev/hello
Authorization: DEV

### 운영
GET http://localhost:8070/real/hello
Authorization: PRODUCTION

###
